package coffee.server.common.exception;

public enum ErrorCode {
    COFFEE_NOT_FOUND,
    COFFEE_DICONTINUED,
    COFFEE_INSUFFICIENT_STOCK,
    COFFEE_NEGATIVE_COFFEE_STOCK,
    COFFEE_NEGATIVE_COFFEE_ORDER_COUNT,

    POINT_NOT_FOUND,
    POINT_INSUFFICIENT_AMOUNT,

    IDEMPOTENCY_CACHE_DUPLICATE_CACHE_KEY,

    ERROR;
}
