package coffee.server.common.exception;

public enum ErrorCode {
    COFFEE_NOT_FOUND,
    COFFEE_DICONTINUED,
    COFFEE_INSUFFICIENT_STOCK,
    COFFEE_NEGATIVE_COFFEE_STOCK,

    POINT_NOT_FOUND,
    POINT_INSUFFICIENT_AMOUNT,

    ERROR;
}
