services:
  mariadb:
    image: mariadb:11.8.6
    container_name: coffee-mariadb
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
      MARIADB_DATABASE: coffee_db
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "43000:3306"

