spring.application.name=server

spring.datasource.url=jdbc:mariadb://localhost:42000/coffee_db
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true

app.add-test-coffees.enabled=true
app.add-init-point.enabled=true

app.batchjobs.reset-coffee-order-count.cron=0 0 0 * * MON

app.coffee-order-log-url=http://localhost:6969/api/coffee-log
