spring.application.name=server

spring.datasource.url=jdbc:mariadb://localhost:42000/coffee_db
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true

app.point-id-in-database=1

app.add-test-coffees.enabled=true
app.add-init-point.enabled=true

# logging.level.root=debug
